- name: Installing MySQL database for expense project
  hosts: mysql
  become: yes
  tasks: 
  - name: install mysql
    ansible.builtin.dnf:
      name: mysql-server
      state: installed

  - name: Start and enabling the mysql service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: true
  
  - name: mysql information
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      host: 172.31.23.71
    register: mysql_info

  - name: 
    ansible.builtin.debug:
      msg: "{{ mysql_info }}"