- name: Installing MySQL database for expense project
  hosts: mysql
  become: yes
  vars:
    mysql_root_pwd: ExpenseApp@1
    mysql_host: 172.31.23.71

  tasks: 
  - name: Install MySQL libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
      - PyMySQL
      - cryptography

  - name: install mysql
    ansible.builtin.dnf:
      name: mysql-server
      state: installed

  - name: Start and enabling the mysql service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: true
  
  - name: collecting mysql database information
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_pwd }}"
      login_host: 172.31.23.71
    register: mysql_info
    ignore_errors: true

  - name: print mysql information
    ansible.builtin.debug:
      msg: "{{ mysql_info }}"

  # - name: setup mysql root password
  #   community.mysql.mysql_user:
  #     login_user: root
  #     name: root 
  #     
  #     password: ExpenseApp@1
  #   when: mysql_info.failed is true

  - name: setup root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_pwd }} "
    when: mysql_info.failed is true


