- name: Installing nodejs e for expense project
  hosts: backend_servers
  become: yes
  vars:
    mysql_host: 172.31.17.43
  tasks:
  - name: Disable the nodejs module
    ansible.builtin.command:
      cmd: "dnf module disable nodejs"

  # - name: enable nodejs:20 
  #   ansible.builtin.command: dnf module enable nodejs:20

  # - name: installing nodejs and mysql
  #   ansible.builtin.debug:
  #     name: "{{ item }}"
  #     state: installed
  #   loop:
  #   - nodejs
  #   - mysql
    
    