- name: Installing nginx for expense project
  hosts: frontend_servers
  become: yes
  tasks:
  - name: Installing nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed
  
  - name: Start and enable the nginx service 
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: true

  - name: Removing nginx default content
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent
  
  # - name: find the the files in html directory
  #   ansible.builtin.find:
  #     paths: /usr/share/nginx/html # The directory path you want to clean
  #     recurse: yes  # Recurse to find files in subdirectories
  #     # file_type: file  # Ensure it only finds files
  #   register: files_to_remove

  # - name: Recursively remove default nginx directory
  #   ansible.builtin.file:
  #     path: "{{ item.path }}"
  #     state: absent  # Delete the file
  #   loop: "{{ files_to_remove.files }}"
  # - name: creating html
  #   ansible.builtin.file:
  #     path: /usr/share/nginx/html
  #     state: directory

  - name: Download and unzip the frontend content
    ansible.builtin.unarchive:
      src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /usr/share/nginx/html/
      remote_src: yes
  
  - name: copy expense config
    ansible.builtin.copy:
      src: /home/ec2-user/ansible_expense_project/03-expense.conf
      dest: /etc/nginx/default.d/expense.conf
      

  - name: Start and enable the nginx service 
    ansible.builtin.service:
      name: nginx
      state: restarted